In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
sns.set_style('whitegrid')
sns.set_palette("husl")

plt.rcParams['figure.figsize'] = (12,6)
plt.rcParams['font.size'] = 11
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.labelsize'] = 12
%matplotlib inline

In [4]:
df = pd.read_csv('zomato.csv', encoding='latin-1')

# choosing encoding = "latin-1" here , because it handles the special characters in names.

In [5]:
# PRECAUTION : Saving the dataframe , (just in c ase if something got deleted from the df doing cleaning )

df_original = df.copy()

In [6]:
print("Shape: ", df.shape)

Shape:  (51717, 17)

In [7]:
print("\nColumns:" , df.columns.tolist())

Columns: ['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes', 'phone', 'location', 'rest_type', 'dish_liked', 'cuisines', 'approx_cost(for two people)', 'reviews_list', 'menu_item', 'listed_in(type)', 'listed_in(city)']

In [8]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  str
 1   address                      51717 non-null  str
 2   name                         51717 non-null  str
 3   online_order                 51717 non-null  str
 4   book_table                   51717 non-null  str
 5   rate                         43942 non-null  str
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  str
 8   location                     51696 non-null  str
 9   rest_type                    51490 non-null  str
 10  dish_liked                   23639 non-null  str
 11  cuisines                     51672 non-null  str
 12  approx_cost(for two people)  51371 non-null  str
 13  reviews_list                 51717 non-null  str
 14  menu_item                    51717 non-null  str
 15  listed_in(type)              51717 non-null  str
 16  listed_in(city)              51717 non-null  str
dtypes: int64(1), str(16)
memory usage: 6.7 MB

In [10]:
df.describe()

#statistical summary of numeric columns

              votes
count  51717.000000
mean     283.697527
std      803.838853
min        0.000000
25%        7.000000
50%       41.000000
75%      198.000000
max    16832.000000

In [11]:
df.describe(include="object")

#stat summary of text columns

,url,address,name,online_order,book_table,rate,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
count,51717,51717,51717,51717,51717,43942,50509,51696,51490,23639,51672,51371,51717,51717,51717,51717
unique,51717,11495,8792,2,2,64,14926,93,93,5271,2723,70,22513,9098,7,30
top,https://www.zomato.com/bangalore/jalsa-banasha...,Delivery Only,Cafe Coffee Day,Yes,No,NEW,080 43334321,BTM,Quick Bites,Biryani,North Indian,300,[],[],Delivery,BTM
freq,1,128,96,30444,45268,2208,216,5124,19132,182,2913,7576,7595,39617,25942,3279

In [12]:
print("Null counts:")
df.isnull().sum()

Null counts:

url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                            7775
votes                              0
phone                           1208
location                          21
rest_type                        227
dish_liked                     28078
cuisines                          45
approx_cost(for two people)      346
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [13]:
# Calc % of Null vals in respective columns
print("Null % per column:")
((df.isnull().sum()/len(df))*100).round(3)

Null % per column:

url                             0.000
address                         0.000
name                            0.000
online_order                    0.000
book_table                      0.000
rate                           15.034
votes                           0.000
phone                           2.336
location                        0.041
rest_type                       0.439
dish_liked                     54.292
cuisines                        0.087
approx_cost(for two people)     0.669
reviews_list                    0.000
menu_item                       0.000
listed_in(type)                 0.000
listed_in(city)                 0.000
dtype: float64

In [14]:
#Unique val per column

print("Unique Values : ")
print(df.nunique() )

Unique Values :
url                            51717
address                        11495
name                            8792
online_order                       2
book_table                         2
rate                              64
votes                           2328
phone                          14926
location                          93
rest_type                         93
dish_liked                      5271
cuisines                        2723
approx_cost(for two people)       70
reviews_list                   22513
menu_item                       9098
listed_in(type)                    7
listed_in(city)                   30
dtype: int64

In [15]:
# Duplicate rows 

print("Duplicate rows: ", df.duplicated().sum())

Duplicate rows:  0

# Data Preprocessing

## 1. Removing Useless Columns

Since this project does not involve NLP tasks, the following text-based columns are removed:

- `url`
- `phone`
- `reviews_list`
- `menu_item`
- `dish_liked`

## 2. Data Type Conversion

The following columns are converted to appropriate numerical data types:

- `rate`: `str` → `float`
- `approx_cost`: `str` → `int`

## 3. Binary Encoding

The following categorical columns are encoded into binary values:

- `online_order`: `Yes` → `1`, `No` → `0`
- `book_table`: `Yes` → `1`, `No` → `0`

### Removing Useless Colums

In [16]:
print("\nColumns:" , df.columns.tolist())

Columns: ['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes', 'phone', 'location', 'rest_type', 'dish_liked', 'cuisines', 'approx_cost(for two people)', 'reviews_list', 'menu_item', 'listed_in(type)', 'listed_in(city)']

In [17]:
cols_removed = ["url", "phone", "reviews_list" ,"menu_item"]

In [18]:
df.drop(columns = cols_removed, inplace=True)

In [19]:
print("Remaining Columns: ", df.columns.tolist())

Remaining Columns:  ['address', 'name', 'online_order', 'book_table', 'rate', 'votes', 'location', 'rest_type', 'dish_liked', 'cuisines', 'approx_cost(for two people)', 'listed_in(type)', 'listed_in(city)']

### Renaming Columns for clarity

In [20]:
df.rename(columns={ 

    "approx_cost(for two people)": "cost_for_two",
    "listed_in(type)" : "meal_type",
    "listed_in(city)" : "city",
    
}, inplace=True)


print(df.columns.tolist())

['address', 'name', 'online_order', 'book_table', 'rate', 'votes', 'location', 'rest_type', 'dish_liked', 'cuisines', 'cost_for_two', 'meal_type', 'city']

### Removing Duplicates (if any)

In [21]:
# Duplicate rows 

print("Duplicate rows ( Before ): ", df.duplicated().sum())

Duplicate rows ( Before ):  85

In [22]:
#duplicates occurs bcz we removed some columns . 
df.drop_duplicates(inplace = True)
df.reset_index(drop=True, inplace = True)
print("Duplicates after: ", df.duplicated().sum())
print("Shape after dedup: ", df.shape)

Duplicates after:  0
Shape after dedup:  (51632, 13)

### Fixing the "rate" column
 Because this column contains many incosistent values ,
 which includes :
 - Ratings in the format `"4.5/5"` : will change this to float , and remove "/5"
 - Special vals such as : `"NEW"` and `"-"`
 - Missing vals : `"NaN"`

  At first ,Will change special vals to NaN
  then `"NaN"` with median or will see possibility to drop it. 

  Then will change the data type from `"str"` to `"float"`

In [23]:
print(df["rate"].unique()[:25])

<StringArray>
[ '4.1/5',  '3.8/5',  '3.7/5',  '3.6/5',  '4.6/5',  '4.0/5',  '4.2/5',
  '3.9/5',  '3.1/5',  '3.0/5',  '3.2/5',  '3.3/5',  '2.8/5',  '4.4/5',
  '4.3/5',    'NEW',  '2.9/5',  '3.5/5',      nan,  '2.6/5', '3.8 /5',
  '3.4/5',  '4.5/5',  '2.5/5',  '2.7/5']
Length: 25, dtype: str

In [24]:
print(df["rate"].dtype)

str

In [25]:
#Removing "/5" first 

df["rate"] = df["rate"].astype(str).str.replace("/5", "", regex=False).str.strip()

In [26]:
df["rate"] = df["rate"].replace(["NEW", "-", "nan", " -", ""], np.nan)
df["rate"].isnull().sum()

np.int64(10030)

In [27]:
df["rate"] = pd.to_numeric(df["rate"], errors="coerce")
df["rate"].dtype

dtype('float64')

In [28]:
df["rate"].describe()

count    41602.000000
mean         3.700082
std          0.440417
min          1.800000
25%          3.400000
50%          3.700000
75%          4.000000
max          4.900000
Name: rate, dtype: float64

In [29]:
# percentage of null/nan values : 
print("Percentage of nan values : ")
(df["rate"].isnull().sum()/len(df) )*100

Percentage of nan values :

np.float64(19.42593740316083)

#### since we dont want to loose `~20% data` , will replace these nan values with `median` .

In [30]:
df["rate"] = df["rate"].fillna(df["rate"].median(), inplace = True)

print("Rate range:", df["rate"].min(),"to",df["rate"].max())

Rate range: 1.8 to 4.9

In [31]:
print(df["rate"].unique()[:65])

[4.1 3.8 3.7 3.6 4.6 4.  4.2 3.9 3.1 3.  3.2 3.3 2.8 4.4 4.3 2.9 3.5 2.6
 3.4 4.5 2.5 2.7 4.7 2.4 2.2 2.3 4.8 4.9 2.1 2.  1.8]

In [32]:
df["rate"].isna().sum()

np.int64(0)

### Fixing the cost Column

The `approx_cost(for two people)` column contains cost vals in string format and includes `" , "`, which makes it unsuitable for numerical analysis.

To clean this column, the following steps are performed:

1. Rename the column for simplicity.
2. Remove commas from values (e.g., "1,200" → "1200").
3. Convert the column from `string` to `integer` type.

In [34]:
print(df["cost_for_two"].unique()[:100])

<StringArray>
[  '800',   '300',   '600',   '700',   '550',   '500',   '450',   '650',
   '400',   '900',   '200',   '750',   '150',   '850',   '100', '1,200',
   '350',   '250',   '950', '1,000', '1,500', '1,300',   '199',    '80',
 '1,100',   '160', '1,600',   '230',   '130',    '50',   '190', '1,700',
     nan, '1,400',   '180', '1,350', '2,200', '2,000', '1,800', '1,900',
   '330', '2,500', '2,100', '3,000', '2,800', '3,400',    '40', '1,250',
 '3,500', '4,000', '2,400', '2,600',   '120', '1,450',   '469',    '70',
 '3,200',    '60',   '560',   '240',   '360', '6,000', '1,050', '2,300',
 '4,100', '5,000', '3,700', '1,650', '2,700', '4,500',   '140']
Length: 71, dtype: str

### Removing the ` '' ` and converting dtype from str -> int

In [35]:
df["cost_for_two"] = df["cost_for_two"].astype(str).str.replace(",", "", regex=False)

In [36]:
df["cost_for_two"] = pd.to_numeric(df["cost_for_two"], errors="coerce")

In [37]:
print(df["cost_for_two"].unique()[:100])

[ 800.  300.  600.  700.  550.  500.  450.  650.  400.  900.  200.  750.
  150.  850.  100. 1200.  350.  250.  950. 1000. 1500. 1300.  199.   80.
 1100.  160. 1600.  230.  130.   50.  190. 1700.   nan 1400.  180. 1350.
 2200. 2000. 1800. 1900.  330. 2500. 2100. 3000. 2800. 3400.   40. 1250.
 3500. 4000. 2400. 2600.  120. 1450.  469.   70. 3200.   60.  560.  240.
  360. 6000. 1050. 2300. 4100. 5000. 3700. 1650. 2700. 4500.  140.]

#### Tackling with nulls

In [39]:
print("Null cost: ")
print(df["cost_for_two"].isnull().sum())

Null cost:
344